### ISSUE TITLE
Different results on command line tool and the web Application

### ISSUE THREAD

**Issue by bhushangawde** [plemeri/transparent-background#2]
Hello,

Thanks for sharing this brilliant tool. However, when I run the command line tool on a set of images to get the maps, the results I receive are very different and are not as accurate as the results I received after using the web interface(https://huggingface.co/spaces/taskswithcode/salient-object-detection) on the same set of images.  

I am pretty sure I am following all the steps according to the README.

Btw, I installed the tool using pip and I am using conda environment on windows.

**Comment by plemeri** [comment]
Hi, thank you for trying both of our repositories. It is because they do not use the same checkpoint. For the main repository InSPyReNet, the huggingface demo, is trained only with DUTS with low resolution datasets. This repository on the other hand, is trained with all the datasets we can access including test datasets to maximize the performance for real world application which is also accessible in [Model Zoo](https://github.com/plemeri/InSPyReNet/blob/main/docs/model_zoo.md). Also, the config used for train this repository is [Plus_Ultra.yaml](https://github.com/plemeri/InSPyReNet/blob/main/configs/extra_dataset/Plus_Ultra.yaml). You can try this checkpoint on your machine and you can obtain the exact same result as this repository.

Thank you, and feel free to ask more question!

**Comment by bhushangawde** [comment]
Hi,

Thank you for your reply. I tried experimenting with different pre-trained models and config files.
It seems the model trained on only DUTS gave the best results for my specific task!
