### ISSUE TITLE
img_lr never being used (Pyramid Blending)

### ISSUE THREAD

**Issue by Amadeus-AI** [plemeri/transparent-background#24]
Hi, thanks for the great work.
If I didn't miss anything, the pyramid blending is not working with neither base mode nor fast mode.
The fast mode did set the threshold, but in the remover.py, we didn't give the model img_lr, so the pyramid blending would not work properly when the img size is larger then threshold if I understand it correctly. They will all be resize to 384x thus not using pyramid blending. Is there a mode for pyramid blending missing?

**Comment by plemeri** [comment]
Yes you're right. Because pyramid blending is useful only when high resolution datasets are **unavailable**. Since this repository is created to provide a maximum capability of our network architecture with massive dataset composition, we do not need pyramid blending. 

FYI, thanks to the image pyramid structure used in the InSPyReNet architecture, our method with high resolution dataset outperforms other HR methods, so pyramid blending is unnecessary since it is a post-processing procedure which requires additional memory & computational cost.
