### ISSUE TITLE
About the data set corresponding to the open weight

### ISSUE THREAD

**Issue by babyta** [plemeri/transparent-background#37]
Thanks to the author for your work. What I want to know is which data sets are used to train the fast and base models? Plus_Ultra?
There is another question: what does the base-nightly model mean and its application scenarios?

**Comment by plemeri** [comment]
Hi @babyta, please refer to our original work [InSPyReNet](https://github.com/plemeri/InSPyReNet) and [model_zoo](https://github.com/plemeri/InSPyReNet/blob/main/docs/model_zoo.md#-trained-with-massive-sod-datasets-with-lr-384-x-384-and-hr-1024-x-1024-not-in-the-paper-for-real-world-scenarios). 

`base-nightly` is trained with improved training method which I was planning to release soon but postponed due to my graduation. I'm not sure that I can spear some time to do so.

Thanks.

**Comment by wilfrediscoming** [comment]
@plemeri @babyta The author is truly a genius, keep up with this!! so thankful for this to exist in the world.
