### ISSUE TITLE
only Partial product is masked

### ISSUE THREAD

**Issue by dineshiitkgp** [plemeri/transparent-background#53]
In the case image comprises of product within a product, it could segment only one product. Attached the image for reference.

for example,
In the case of television example, I want mask for whole television but it segments only football. could you help why model only segments football and what could be done to get mask for whole television.

Similar in the case of trash bag example case. I want mask for whole rectangle but it mask only trash bag.

![Screenshot 2024-01-24 at 2 43 35 PM](https://github.com/plemeri/transparent-background/assets/11491858/34558672-5cee-44e4-b14a-a24bc3c2c8da)
![Screenshot 2024-01-24 at 2 57 51 PM](https://github.com/plemeri/transparent-background/assets/11491858/abbb5cae-6893-47bc-b0b1-d2e664e7bb35)

**Comment by plemeri** [comment]
Those are expected results. Our method is based on Salient Object Detection, which predicts the saliency map of the most salient object. In the provided images, for me the most salient objects are football and trash bag. First one could be controversial, someone might say the whole TV, but it depends on each person's thought. Because of that, SOD is often regarded as an ill-posed problem, it means that there are no single answer for the question. If you need a half-automation, then you might want to look for the Segment Anything and its related methods since they offer you to provide various extra query options such as text input or coordinates in the image. If you need a full-automation, I suggest you to create your own dataset and train the model with our github repo https://github.com/plemeri/InSPyReNet.
