### ISSUE TITLE
how to use SPyReNet_Res2Net50 with size 384 X 384 and mode nightly-base?

### ISSUE THREAD

**Issue by mikebilly** [plemeri/transparent-background#54]
please provide example code how to use models from here: 
https://github.com/plemeri/InSPyReNet/blob/main/docs/model_zoo.md

for example, how to use the first custom model:

Backbone   Train DB          Config
Res2Net50 DUTS-TR InSPyReNet_Res2Net50

**Comment by plemeri** [comment]
mode `nightly-base` is specifically for the fast model release which I just added somewhat randomly. Currently, models with Res2Net backbone is not supported since the model architecture is hard coded to the SwinB models. If you are advanced user, you'll know the drill. Otherwise, please use https://github.com/plemeri/InSPyReNet/blob/main/run/Inference.py which is technically identical to this package.

**Comment by plemeri** [comment]
It depends. Mostly, just use `base` option which you do not need to specify.
