### ISSUE TITLE
2 questions related to config and models

### ISSUE THREAD

**Issue by nitinmukesh** [plemeri/transparent-background#68]
1. I see this update but  there is no config file

[New] Configuration
transparent-background now supports external configuration rather than hard coded assets (e.g., checkpoint download url).
The config file will be added in your home directory ~/.transparent-background/config.yaml

<img width="581" alt="image" src="https://github.com/user-attachments/assets/fa404b10-8025-4d65-b4d0-66e91cff163a">

2. How to use different model in UI. In which folder should the model be placed and how to select in UI. I did a complete search but no PTH file found in the installation directory. The UI is working fine,
<img width="659" alt="image" src="https://github.com/user-attachments/assets/99412e3e-9a56-4a7a-a427-2b5a8442eb14">

**Comment by plemeri** [comment]
Hi @nitinmukesh 
1. For windows users, home directory will be your user directory (e.g., C:\Users\[username]\.transparent-background)
2. You can choose base / base-nightly / fast model by choosing from dropdown menu `mode`. I didn't add custom mode since at that level of skill, I don't think the user need GUI.
