### ISSUE TITLE
Is there any way to preserve more objects in image?

### ISSUE THREAD

**Issue by Qianvenh** [plemeri/transparent-background#72]
Thanks for your effort. `transparent-background` is the best rmbg library I've seen.
And if I want to keep the tree in this image, what should I do? The Threshold seems not to work in this situation.

Original:
![1722153631954365](https://github.com/user-attachments/assets/83b2e511-f20f-4ce5-ba4c-a17299b1df25)

Threshold 0.05:
![output_17225169617344928](https://github.com/user-attachments/assets/d81ff362-c505-4e9b-8a7d-97d47f2fb618)

default:
![default](https://github.com/user-attachments/assets/8dd1f6af-d3b0-4008-a167-355d3d15fa7d)

**Comment by plemeri** [comment]
Hi @Qianvenh, first of all, thanks for enjoying our work. Our method, including other background removal methods are trained with salient object detection datasets. Salient object means the most salient, in other words the most dominant object in the given scene. Because of that, you'll get similar results from other ways like remove.bg or background removal tool from apple products. 

In this case, the guitar is obviously the most important object while the tree in the background is cropped by the image frame, so it implies that the tree is not important. If the tree should be treated as an important object, the image should have been taken with the tree inside the image frame.

Someone would say that this is not a truly background removal, but this project wasn't actually made for the background only removal, rather it was to extract the most important object from the given image. So, while using our project, it would be better keep this information in mind, then you'll get the result as expected more easily. 

If you still want to extract the tree part and the guitar at the same time, you might want to do some research on methods with prompt support which remove.bg is capable of.  

Thank you.

**Comment by Qianvenh** [comment]
Thank you for your so prompt reply. This will undoubtedly help me make better use of transparent-background!

**Comment by plemeri** [comment]
Much appreciated for your support!
